### ISSUE TITLE
DataSet Column name issue

### ISSUE THREAD

**Issue by jang-1996** [gume-gume/MLOps-project#1]
우리의 데이터 셋의 컬럼명에 점(.) 이 있는 부분이 있는데  
본래의 데이터 컬럼명의 점을 다른 것으로 수정하거나 
아예 컬럼명으로 수정하는 것에 대한 의논이 필요해보입니다.

**Comment by tjsrb63** [comment]
> 우리의 데이터 셋의 컬럼명에 점(.) 이 있는 부분이 있는데 본래의 데이터 컬럼명의 점을 다른 것으로 수정하거나 아예 컬럼명으로 수정하는 것에 대한 의논이 필요해보입니다.

> 그러면 .을 _로 바꿔서 진행하는건 어떨까요??

**Comment by bigtrader91** [comment]
네, 저도 언더바로 바꾸면 될듯 합니다~

**Comment by jang-1996** [comment]
넵 언더바로 진행하겠습니다~!

**Comment by jang-1996** [comment]
HEK
