### ISSUE TITLE
<chore> How about changing the database?

### ISSUE THREAD

**Issue by jang-1996** [gume-gume/MLOps-project#16]
### ✔ 실현 불가능한 이유
    기존의 postgresql 일때 전체 데이터 받아오는 속도가 느림. 리눅스,MacOs 환경에 따라 조금씩 다름. (ex - 리눈스에서는 pgAdmin지원안됨)

    각 로컬 컴퓨터 별로 세팅을 해야하기에 키만 필요한 S3 storage가 적절해 보입니다.
    
    
### ✔ 하고싶은 말(optional)
    따라서 기존의 postgresql에서 클라우드 S3로 변경하는 것은 어떠한지 질문하고 싶습니다.

**Comment by tjsrb63** [comment]
클라우드 사용할 때 얼마정도 드는지 한번 확인해 봐야할 것 같아요
+ 저도 받아올 때 속도가 좀 느리긴 했습니다.

**Comment by bigtrader91** [comment]
저도 변경하는게 좋아보입니다.

S3으로 변경 관련해서 아래 링크 참고하면 좋을듯 합니다.

[AWS S3 이미지생성](https://buildabetterworld.tistory.com/173)

**Comment by bigtrader91** [comment]
postgresql 으로 계속하면 될듯하고, s3는 mlflow 할때 사용하면 될듯 합니다~

이슈 닫을게요~
