### ISSUE TITLE
<error> read all data in database 

### ISSUE THREAD

**Issue by jang-1996** [gume-gume/MLOps-project#19]
### ✔코드경로(line 포함)
routers/db.py

```
@router.get('/incomes', response_model=List[People])
def get_all_incomes():
    incomes = db.query(People_Table).all()
    print( 'income ',incomes)    
    return incomes
```
    
    
### ✔ 오류
        
    터미널에서는 데이터가 잘 불러와지는데 Swagger에서는 서버가 튕깁니다
    
### ✔ 버그에 대한 뇌피셜
    
    데이터를 리스트 형식으로 받아오지 않아 생기는 현상인거 같습니다. 그리고 데이터 수가 많아서 서버가 버티지 못할 수 도 있을거 같네요
    
    
    
### ✔  하고싶은 말(optional)
   오전 안으로 버그 수정해보겠습니다.

**Comment by jang-1996** [comment]
id = 17195 부터 none is not an allowed value메세지가 보입니다. null 데이터가 있는 것으로 보여집니다. 테이블 생성시 null 값 허용을 해보겠습니다.

**Comment by jang-1996** [comment]
Optional 은 실패...

**Comment by tjsrb63** [comment]
저도 해보고 있는데

1. ```
@router.get('/incomes', response_model=List[People])
   def get_all_incomes():
```  실패..

2. models에서 id 관련해서 에러라 생각하고 리턴값에 id를 추가해서 실행했지만 실패 ㅋ.ㅋ

**Comment by jang-1996** [comment]
```
@router.get('/incomes')
def get_all_incomes():
    conn_string = "host = 'localhost' dbname = 'income_db' user = 'postgres' password = '1234'"
    conn = psycopg2.connect(conn_string)
    cur = conn.cursor()
    cur.execute('SELECT * FROM people_income;')
    result = np.array(cur.fetchall())
    print(result)
    my_df = pd.DataFrame(result)   
    return print(my_df)
```

sql 쿼리 문으로 데이터를 불러온 후 데이터 프레임으로 불러오니 빠르게 받아와집니다 ^^ 하지만 현재 컬럼명이 사라져서 컬럼명을 살리는 작업 하겠습니다.

**Comment by jang-1996** [comment]
데이터프레임으로 받아오는 방식으로 해결되었습니다.
그리고 저희 프로젝트에 한 행씩 받아오는 기능은 토의 끝에 필요없다는 결과가 나와서 def get_an_income(income_id:int): 함수는 삭제하겠습니다.
