### ISSUE TITLE
[QUESTION] can server make independency?

### ISSUE THREAD

**Issue by jang-1996** [gume-gume/MLOps-project#45]
### ❓ 질문내용
 
클라우드 서버 상으로 개발할 때, 누군가 서버를 열면 다른 누군가가 uvicorn main:app 실행시 접속 불가입니다. localhost: 로 들어가면 가능은 하지만 코드 수정사항이 서버에 적용이 되지 않는거 같습니다. 

이에 해결 방안을 찾고자 이슈에 올립니다.

**Comment by bigtrader91** [comment]
loguru 를 사용해서 로그찍으면 될것같습니다~
