### ISSUE TITLE
[BUG] minio server error

### ISSUE THREAD

**Issue by bigtrader91** [gume-gume/MLOps-project#74]
### ✔코드경로(line 포함)
- minio 서버 실행  커맨드를 아래와 같이 입력

`~/minio server /mnt/data —console-address ":9001"`

### ✔ 오류메시지
```

ERROR Invalid command line arguments: Incorrect number of endpoints provided [/mnt/data —console-address localhost:9001]
      > Please provide an even number of endpoints greater or equal to 4
      HINT:
        For more information, please refer to https://docs.min.io/docs/minio-erasure-code-quickstart-guide
```

### ✔ 버전정보
python 3.9.7

### ✔ 버그에 대한 뇌피셜
4보다 크거나 같은 짝수 엔드포인트가 뭘 의미하는지 알 수 없음.

**Comment by SSunQ** [comment]
minio 도커로 생성 완료
포트에 9001 추가후 localhost:9001 들어가면 이제 열릴겁니다!
