### ISSUE TITLE
[BUG] port 5432 connection error

### ISSUE THREAD

**Issue by bigtrader91** [gume-gume/MLOps-project#80]
### ✔코드경로(line 포함)
- uvcorn main:app --reload  실행시 아래와 같은 에러메시지 발생

### ✔ 오류메시지
```
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

### ✔ 버전정보
python 3.9.7

### ✔ 버그에 대한 뇌피셜
- postgres 관련 문제로 생각됩니다.

### ✔  하고싶은 말(optional)
-  별도 조치를 하지 않았으나 30~40분 이후 정상 작동

**Comment by SSunQ** [comment]
mlflow도 같은 에러가 납니다 
저는 아직도 같은 에러가 납니다

**Comment by jang-1996** [comment]
```
conn = psycopg2.connect(host =settings.DB_ADDRESS,
                        database = settings.DB_NAME,
                        user = settings.DB_ID,
                        password =settings.DB_PASSWORD)

```
database.py 부분의 ADDRESS에서 에러가 나오는 듯 합니다.

**Comment by bigtrader91** [comment]
airflow  도커로 설치시 포트중복으로 인한 충돌로 생각됩니다. 

현재 도커 compose 가 아닌 직접 airflow 설치하여 해결됐습니다.

**Comment by bigtrader91** [comment]
airflow 도커로 설치시 포트중복으로 인한 충돌로 생각됩니다.

현재 도커 compose 가 아닌 직접 airflow 설치하여 해결됐습니다.
