### ISSUE TITLE
[BUG]  save the model directly to the minio

### ISSUE THREAD

**Issue by jang-1996** [gume-gume/MLOps-project#81]
### ✔코드경로(line 포함)
app/service/app_service.py 의 112번째줄
```
  def model_save(self, model, names):
        minio_client.put_object(
        "income", joblib.dump(model, f"{names}.pkl", compress=3) ,BytesIO(b"hello"), 5
        )    
```

### ✔ 버전정보
python 3.9.7

### ✔ 버그에 대한 뇌피셜

로컬에 모델을 저장 후 로컬에 저장된 모델을 minio에 저장하는 것은 가능합니다.
하지만 비효율적이라는 판단이 들어 바로 minio에 저장하게 구현 중입니다.
좋은 의견이 있으면 언제든지 말씀해주세요.

**Comment by bigtrader91** [comment]
minio로 직접 저장할 필요는 없고 mlflow 로 관리하면 될듯합니다~
