### ISSUE TITLE
[BUG] docker automatically stop

### ISSUE THREAD

**Issue by jang-1996** [gume-gume/MLOps-project#90]
### ✔코드
Dockerfile
```
FROM continuumio/miniconda3

WORKDIR /app

COPY . /app

RUN pip install -r requirements.txt

CMD uvicorn main:app --host 0.0.0.0 --port 8000

EXPOSE 8000
```

이미지 빌드
```
1. sudo docker build [이미지명]
2. sudo docker run -d -p 80:8080 [이미지]
3. sudo docker ps
```
### ✔ 오류

도커 실행 후 실행 중인 이미지를 확인하면 자동으로 꺼짐

### ✔ 버그에 대한 뇌피셜

도커는 내부에서 실행 중인 프로세스가 없으면 자동으로 종료한다고 나와있습니다.
따라서 도커파일내에 프로세스를 유지시키는 CMD 작성해야할거같습니다.

### ✔  참고자료

https://www.tutorialworks.com/why-containers-stop/
https://bslife.tistory.com/86

**Comment by SSunQ** [comment]
저도 같은 현상입니다
이미지명을 mlops/mlops로 만든 후

docker run -t -d mlops/mlops -p 8000:8000 tail -f /dev/null로
해보았는데 종료되지는 않는데 서버가 들어가지지는 않습니다.

참고자료 : http://daplus.net/docker-docker-run-d%ED%9B%84%EC%97%90-docker- %EC%BB%A8%ED%85%8C%EC%9D%B4%EB%84%88%EA%B0%80-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EC%A4%91%EC%A7%80%EB%90%A9%EB%8B%88%EB%8B%A4/

**Comment by SSunQ** [comment]
-p 외부포트와 연결

docker run -d -p 8000:8000 -p 5432:5432 -p 6379:6379 fastapi:v1
- > 계속 써야하니 귀찮음의 문제가 있음

Network host : 컨테이너의 네트워크와 내 컴퓨터의 네트워크를 동기화
내 컴퓨터에서 직접 띄운것처럼 

docker run -d --network host [images 명]
